name: Run ESLint
on: [pull_request]

env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: install dependencies
        run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: "src/"
          fail_on_error: "true"
          level: "warning"